### ISSUE TITLE
Error on Step 5 - Version Mismatch

### ISSUE THREAD

**Issue by adamrandazzo** [akeneo/transporteo#93] opened 2017-10-10 14:40 UTC
On step 5 of migrating from a remote server to a new local server, I receive the following error:

```
[Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimInstallationException]
  Error: Step 5 - Destination PIM installation: Your destination PIM version should be 2.0.x currently : ~2.0.1
```
```  [Akeneo\PimMigration\Domain\MigrationStep\s050_DestinationPimInstallation\DestinationPimDetectionException]
  Your destination PIM version should be 2.0.x currently : ~2.0.1
```
This is a brand new local installation from composer

**Comment by LaurentPetard** [comment] 2017-10-10 15:51
Hello @adamrandazzo 

Thanks for reporting this issue. The problem is that the check of the PIM version doesn't handle the character "~" before the version number.

This will be fixed as soon as possible, but in the meantime you can fix it by removing this character in the  file composer.json of the PIM 2.0 (at the line "akeneo/pim-community-dev" in "require",  the value would be "2.0.1" instead of "~2.0.1")

**Comment by momoss** [comment] 2017-10-13 12:33
Hello @adamrandazzo,

The issue has been fixed and will be in the next patch released very soon, so I close the issue.

Best regards.

**Closed by momoss** 2017-10-13 12:33 UTC
Labels: bug
